-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 17:46:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_GRUPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TB_GRUPO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TB_GRUPO` (
  `nome_gp` VARCHAR(200) NOT NULL,
  `descrição_gp` VARCHAR(45) NULL,
  `quant_integrantes` INT NULL,
  PRIMARY KEY (`nome_gp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_CALENDARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TB_CALENDARIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TB_CALENDARIO` (
  `dia` INT NOT NULL,
  `semana` INT NULL,
  `mes` INT NULL,
  `ano` INT NULL,
  PRIMARY KEY (`dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TB_USUARIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TB_USUARIO` (
  `nome_usuario` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(200) NULL,
  `email_usuario` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cidade` VARCHAR(120) NULL,
  `senha` BINARY(32) NOT NULL,
  PRIMARY KEY (`nome_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_EVENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TB_EVENTO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TB_EVENTO` (
  `nome_evento` VARCHAR(200) NOT NULL,
  `hora_inicio` VARCHAR(45) NOT NULL,
  `hora_termino` VARCHAR(45) NOT NULL,
  `data_ev` DATE NOT NULL,
  `pais_evento` VARCHAR(45) NOT NULL,
  `estado_ev` VARCHAR(45) NOT NULL,
  `cidade_ev` VARCHAR(45) NOT NULL,
  `bairro_ev` VARCHAR(45) NOT NULL,
  `rua_ev` VARCHAR(45) NOT NULL,
  `complemento_endev` VARCHAR(45) NULL,
  `participantes_ev` INT NULL,
  `importancia_ev` ENUM('Baixa', 'Media', 'Alta') NULL,
  `TB_GRUPO_nome_gp` VARCHAR(200) NOT NULL,
  `TB_USUARIO_nome_usuario` VARCHAR(200) NOT NULL,
  `TB_USUARIO_TB_CALENDARIO_dia` INT NOT NULL,
  PRIMARY KEY (`nome_evento`, `TB_GRUPO_nome_gp`, `TB_USUARIO_nome_usuario`, `TB_USUARIO_TB_CALENDARIO_dia`),
  INDEX `fk_TB_EVENTO_TB_GRUPO1_idx` (`TB_GRUPO_nome_gp` ASC) VISIBLE,
  INDEX `fk_TB_EVENTO_TB_USUARIO1_idx` (`TB_USUARIO_nome_usuario` ASC, `TB_USUARIO_TB_CALENDARIO_dia` ASC) VISIBLE,
  CONSTRAINT `fk_TB_EVENTO_TB_GRUPO1`
    FOREIGN KEY (`TB_GRUPO_nome_gp`)
    REFERENCES `mydb`.`TB_GRUPO` (`nome_gp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_EVENTO_TB_USUARIO1`
    FOREIGN KEY (`TB_USUARIO_nome_usuario` , `TB_USUARIO_TB_CALENDARIO_dia`)
    REFERENCES `mydb`.`TB_USUARIO` (`nome_usuario` , `TB_CALENDARIO_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_CALENDARIO_has_TB_EVENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TB_CALENDARIO_has_TB_EVENTO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TB_CALENDARIO_has_TB_EVENTO` (
  `TB_CALENDARIO_dia` INT NOT NULL,
  `TB_EVENTO_nome_evento` VARCHAR(200) NOT NULL,
  `TB_EVENTO_TB_GRUPO_nome_gp` VARCHAR(200) NOT NULL,
  `TB_EVENTO_TB_USUARIO_nome_usuario` VARCHAR(200) NOT NULL,
  `TB_EVENTO_TB_USUARIO_TB_CALENDARIO_dia` INT NOT NULL,
  PRIMARY KEY (`TB_CALENDARIO_dia`, `TB_EVENTO_nome_evento`, `TB_EVENTO_TB_GRUPO_nome_gp`, `TB_EVENTO_TB_USUARIO_nome_usuario`, `TB_EVENTO_TB_USUARIO_TB_CALENDARIO_dia`),
  INDEX `fk_TB_CALENDARIO_has_TB_EVENTO_TB_EVENTO1_idx` (`TB_EVENTO_nome_evento` ASC, `TB_EVENTO_TB_GRUPO_nome_gp` ASC, `TB_EVENTO_TB_USUARIO_nome_usuario` ASC, `TB_EVENTO_TB_USUARIO_TB_CALENDARIO_dia` ASC) VISIBLE,
  INDEX `fk_TB_CALENDARIO_has_TB_EVENTO_TB_CALENDARIO1_idx` (`TB_CALENDARIO_dia` ASC) VISIBLE,
  CONSTRAINT `fk_TB_CALENDARIO_has_TB_EVENTO_TB_CALENDARIO1`
    FOREIGN KEY (`TB_CALENDARIO_dia`)
    REFERENCES `mydb`.`TB_CALENDARIO` (`dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_CALENDARIO_has_TB_EVENTO_TB_EVENTO1`
    FOREIGN KEY (`TB_EVENTO_nome_evento` , `TB_EVENTO_TB_GRUPO_nome_gp` , `TB_EVENTO_TB_USUARIO_nome_usuario` , `TB_EVENTO_TB_USUARIO_TB_CALENDARIO_dia`)
    REFERENCES `mydb`.`TB_EVENTO` (`nome_evento` , `TB_GRUPO_nome_gp` , `TB_USUARIO_nome_usuario` , `TB_USUARIO_TB_CALENDARIO_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_USUARIO_has_TB_GRUPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TB_USUARIO_has_TB_GRUPO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TB_USUARIO_has_TB_GRUPO` (
  `TB_USUARIO_nome_usuario` VARCHAR(200) NOT NULL,
  `TB_USUARIO_TB_CALENDARIO_dia` INT NOT NULL,
  `TB_GRUPO_nome_gp` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`TB_USUARIO_nome_usuario`, `TB_USUARIO_TB_CALENDARIO_dia`, `TB_GRUPO_nome_gp`),
  INDEX `fk_TB_USUARIO_has_TB_GRUPO_TB_GRUPO1_idx` (`TB_GRUPO_nome_gp` ASC) VISIBLE,
  INDEX `fk_TB_USUARIO_has_TB_GRUPO_TB_USUARIO1_idx` (`TB_USUARIO_nome_usuario` ASC, `TB_USUARIO_TB_CALENDARIO_dia` ASC) VISIBLE,
  CONSTRAINT `fk_TB_USUARIO_has_TB_GRUPO_TB_USUARIO1`
    FOREIGN KEY (`TB_USUARIO_nome_usuario` , `TB_USUARIO_TB_CALENDARIO_dia`)
    REFERENCES `mydb`.`TB_USUARIO` (`nome_usuario` , `TB_CALENDARIO_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_USUARIO_has_TB_GRUPO_TB_GRUPO1`
    FOREIGN KEY (`TB_GRUPO_nome_gp`)
    REFERENCES `mydb`.`TB_GRUPO` (`nome_gp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`tb_eventos` ;
CREATE TABLE IF NOT EXISTS `mydb`.`tb_eventos` (
	`dia` DATE NOT NULL,
	`horario_comeco` TIME NOT NULL,
	`horario_fim` TIME NOT NULL,
	`modalidade` VARCHAR(64) NOT NULL,
	`importancia` VARCHAR(64) NOT NULL,
	`local` VARCHAR(256) NOT NULL,
  `nome_usuario_fk` VARCHAR(200) NOT NULL,
  FOREIGN KEY (`nome_usuario_fk`) REFERENCES `tb_usuario`(`nome_usuario`)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
